spring:
  activemq:
    broker-url: tcp://localhost:61616
          #?jms.useAsyncSend=true
    packages:
      trusted:
      - com.example.activemq
  jms:
    pub-sub-domain: true
    template:
      delivery-mode: persistent
server:
  port: 8752
topic: workflow
